<div class="page-header">
    <h1><?php echo $this->titulo; ?></h1>
</div>

<table class="table" style="width:700px;">
    <thead>
        <tr> 
            <th>Id</th>
            <th>Nombre</th>
            <th>Apellido</th>
            <th>Detalle</th> 
        </tr>
    </thead>
    <tbody>
        <?php foreach ($this->listaUsuario as $usuario): ?>
            <tr style="background-color:<?php echo $this->cycle(array("#F0F0F0", "#FFFFFF"))->next() ?>">
                <td><?php echo $usuario->getId() ?></td>
                <td><?php echo $usuario->getNombre() ?></td>
                <td><?php echo $usuario->getApellido() ?></td>
                <td>
                    <!-- <a href="<?php echo $this->basePath() ?>/usuario/ver/<?php echo $usuario->getId() ?>">ver</a> -->
                    <a href="<?php echo $this->url('usuario', ['action' => 'ver', 'id' => $usuario->getId()]) ?>">ver</a>
                </td>
            </tr>
        <?php endforeach; ?>
    </tbody>
    <?php
    $this->cycle()->assign(array("#F0F0F0", "#FFFFFF"));
    $this->cycle()->prev();
    ?>
</table>
